# Generated by Django 3.1.1 on 2022-06-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrackOrder',
        ),
        migrations.AddField(
            model_name='order',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_Description',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='product_image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
