# Generated by Django 4.0.5 on 2022-06-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220621_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(max_length=120)),
                ('product_Description', models.CharField(max_length=30000)),
                ('categoty', models.CharField(default='', max_length=20)),
                ('sub_categoty', models.CharField(default='', max_length=20)),
                ('price', models.IntegerField(default='0')),
                ('product_image', models.ImageField(default='', upload_to='shop/images')),
                ('product_Date', models.DateField()),
            ],
        ),
    ]
