# Generated by Django 4.0.6 on 2022-07-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_latest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Orders',
            new_name='Orders_img',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Track_Id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_Description',
        ),
        migrations.AddField(
            model_name='order',
            name='Orders_name',
            field=models.CharField(default='', max_length=1000000000),
        ),
        migrations.AddField(
            model_name='order',
            name='Orders_price',
            field=models.CharField(default='', max_length=1000000000),
        ),
        migrations.AddField(
            model_name='order',
            name='Orders_quantity',
            field=models.CharField(default='', max_length=1000000000),
        ),
        migrations.AddField(
            model_name='order',
            name='Orders_size',
            field=models.CharField(default='', max_length=1000000000),
        ),
    ]
