# Generated by Django 4.0.6 on 2022-08-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_products_product_image_black_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_Description',
            field=models.CharField(default='your order is placed', max_length=150),
        ),
    ]
