# Generated by Django 4.0.6 on 2022-08-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_order_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latest',
            name='product_Description',
        ),
        migrations.RemoveField(
            model_name='latest',
            name='product_image',
        ),
        migrations.AddField(
            model_name='latest',
            name='product_image_black',
            field=models.ImageField(default='null', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='latest',
            name='product_image_blue',
            field=models.ImageField(default='null', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='latest',
            name='product_image_grey',
            field=models.ImageField(default='null', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='latest',
            name='product_image_maroon',
            field=models.ImageField(default='null', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='latest',
            name='product_image_navy',
            field=models.ImageField(default='null', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='latest',
            name='product_image_red',
            field=models.ImageField(default='null', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='latest',
            name='product_image_white',
            field=models.ImageField(default='null', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='latest',
            name='product_image_yellow',
            field=models.ImageField(default='null', upload_to='shop/images'),
        ),
    ]
