# Generated by Django 4.1.7 on 2023-03-31 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_products_product_image_blue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_image_black',
            new_name='product_slide1',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_image_red',
            new_name='product_slide2',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_image_yellow',
            new_name='product_slide3',
        ),
    ]
