# Generated by Django 4.1.7 on 2023-03-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_product_image_black_products_product_slide1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_desc',
            field=models.CharField(default='', max_length=200),
        ),
    ]
