# Generated by Django 4.1.7 on 2023-03-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('product_id', models.CharField(default='', max_length=20)),
                ('review', models.CharField(default='', max_length=20)),
                ('rating', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
