# Generated by Django 4.1.7 on 2023-03-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_Name', models.CharField(max_length=120)),
                ('Food_Description', models.CharField(default='', max_length=200)),
                ('Category', models.CharField(default='', max_length=20)),
                ('sub_categoty', models.CharField(default='', max_length=20)),
                ('Price', models.IntegerField(default='0')),
                ('Product_image', models.ImageField(default='', upload_to='shop/images')),
                ('product_Date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
