# Generated by Django 4.1.7 on 2023-04-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_food_delete_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Latest',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Alternative_Mobile',
        ),
        migrations.RemoveField(
            model_name='order',
            name='landmark',
        ),
        migrations.AddField(
            model_name='order',
            name='Country',
            field=models.CharField(default='', max_length=10),
        ),
    ]
