# Generated by Django 4.1.7 on 2023-04-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_rename_order_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_order',
            name='Mobile',
            field=models.CharField(default='0', max_length=70),
        ),
    ]
