# Generated by Django 4.1.7 on 2023-04-01 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_product_order_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
