# Generated by Django 4.1.7 on 2023-04-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Address',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='register',
            name='Mobile',
            field=models.CharField(default='', max_length=20),
        ),
    ]
